class ExecutiveReportGenerator:

    def __init__(
        self,
        dataset_type,
        quality_report,
        compatibility,
        recommendations,
        insights
    ):

        self.dataset_type = dataset_type
        self.quality = quality_report
        self.compatibility = compatibility
        self.recommendations = recommendations
        self.insights = insights

    def generate_report(self):

        report = f"""
========================================

AI EXECUTIVE BUSINESS REPORT

========================================

Dataset Type:
{self.dataset_type}

Quality Score:
{self.quality['Quality Score']}

Grade:
{self.quality['Grade']}

Compatibility:
{self.compatibility}

Recommended AI Projects:
"""

        for item in self.recommendations:
            report += f"\n• {item}"

        report += "\n\nBusiness Insights:\n"

        for insight in self.insights:
            report += f"\n• {insight}"

        report += """

========================================

Generated by

AI-Driven Decision Intelligence Platform

========================================
"""

        return report